### PR TITLE
Show resource stats for limits too

### PR DESCRIPTION
**Pull request by 2rs2ts**
In reality, resource utilization can be higher than the sum of the
requests of pods in the cluster. Especially for cluster operators who
want node stability, resource limits are much more relevant than
resource requests.

I tried to keep the output format relatively similar as before, though I
thought it might be good to be consistent with the term "CPU" instead of
"cores" and the capitalization "MEMORY" since that was used in one place
and it matches the capitalization of CPU, but that honestly matters
less than just adding output for limits.

### CODE REVIEW

**Comment by 2rs2ts** [comment]
I will change the tests if you OK the output format

**Comment by etopeter** [comment]
Thank you for contributing to the project. I think limits are great add-on feature to have. I would tweak the output format. 
This is inspired by linux df command where everything is clear at a glance. I'm suggesting to put percentage values in own columns for easier parsing in shell scripts.

```
Resource  Req  %Req  Lim  %Lim  Avail
CPU       8.5   42%   26   64%     20
Memory    49G   64%  51G   67%    76G
```
`Avail` available total resources in cluster

For the organization and header naming we could just use same output as `kubectl describe node` have for pods.

```
CPU Requests  CPU Limits  Memory Requests  Memory Limits
```

Any suggestions are welcome. Right now we're using human readable numbers so abbreviations are ok just like `df -h` command.

Abbreviated could look like this:
```
CPU Req  CPU Lim  Mem Req  Mem Lim
```

**Comment by etopeter** [comment]
Skeleton for output is in [more-columns](https://github.com/etopeter/kubectl-view-utilization/tree/more-columns) branch. That branch also implements Free column which right now its only based on requests. Json output and tests will have to be fixed.

**Comment by 2rs2ts** [comment]
I think the changes on master are fine, I will rebase and follow your lead

**Comment by 2rs2ts** [comment]
@etopeter Please let me know what you think of the changes. I also updated the tests this time.

**Comment by etopeter** [comment]
Wonderful! Thank you for this contribution.

**Pull request merged**
